version: 2
jobs:
  build-rust-lfs:
    working_directory: ~/repo
    parallelism: 1
    shell: /bin/bash --login

    docker:
    - image: savannidgerinel/rust:latest

    steps:
    - checkout

    - restore_cache:
        keys:
          # This branch if available
          - dep-{{ .Branch }}-
          # Default branch if not
          - dep-sol-

    - run:
        name: build
        command: |
          cargo build

    - save_cache:
        key: dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cargo

    - run:
        name: test
        command: |
          mkdir var
          RUST_BACKTRACE=1 cargo test

    - save_cache:
        key: dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cargo

  build-rust-nix:
    working_directory: ~/repo
    parallelism: 1

    docker:
    - image: nixos/nix

    steps:
    - checkout
    - run:
        name: build
        command: |
          nix-build

workflows:
  version: 2
  build_all:
    jobs:
      - build-rust-lfs
        # - build-rust-nix
