version: 2
jobs:
  build-nixos:
    working_directory: ~/repo

    docker:
    - image: savannidgerinel/nixos-rust

    steps:
      - checkout

      - restore_cache:
          key: rust-nixos-{{ checksum "server/Cargo.lock" }}

      - run:
          name: update the build channel
          command: |
            nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs-19.03
            nix-channel --update

      - run:
          name: build
          command: |
            nix-build

      - save_cache:
          key: rust-nixos-{{ checksum "server/Cargo.lock" }}
          paths:
            - "/nix/store"

  build-ubuntu:
    working_directory: ~/repo
    parallelism: 1

    docker:
      - image: circleci/rust:1.33-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - dep-ubuntu-{{ checksum "server/Cargo.toml" }}

      - run:
          name: build server
          command: cd server && cargo build --release

      - run:
          name: test server
          command: |
            cd server
            mkdir var
            RUST_BACKTRACE=1 cargo test

      - save_cache:
          key: dep-ubuntu-{{ checksum "server/Cargo.toml" }}
          paths:
            - ~/.cargo

      - restore_cache:
          keys:
            - dep-{{ checksum "client/package-lock.json" }}

      - run:
          name: install javascript dependencies
          command: cd client && npm install

      - run:
          name: build the client
          command: cd client && npm run build

      - run:
          name: test the client
          command: cd client && npm run test

      - save_cache:
          key: dep-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules

      #- run:
          #name: copy components
          #command: |
            #mkdir -p dist/opt/fitnesstrax/bin
            #mkdir -p dist/opt/fitnesstrax/client
            #cp server/target/release/app dist/opt/fitnesstrax/bin/fitnesstrax-server
            #cp client/dist/* dist/opt/fitnesstrax/client

      #- run:
          #name: make deb
          #command: cd dist && fpm -f -s dir -t deb -n fitnesstrax -v `git describe --abbrev=4 HEAD` opt

workflows:
  version: 2
  build_ubuntu:
    jobs:
      - build-ubuntu
