version: 2
jobs:
  build-rust-lfs:
    working_directory: ~/repo
    parallelism: 1
    shell: /bin/bash --login

    docker:
    - image: savannidgerinel/rust:latest

    steps:
    - checkout

    - restore_cache:
        keys:
          # This branch if available
          - dep-{{ checksum "server/Cargo.toml" }}

    - run:
        name: build
        command: |
          cd server
          cargo build

    - save_cache:
        key: dep-{{ checksum "server/Cargo.toml" }}
        paths:
        - ~/.cargo

    - run:
        name: test
        command: |
          cd server
          mkdir var
          RUST_BACKTRACE=1 cargo test

    - save_cache:
        key: dep-{{ checksum "server/Cargo.toml" }}
        paths:
        - ~/.cargo

  build-rust-nix:
    working_directory: ~/repo
    parallelism: 1

    docker:
    - image: nixos/nix

    steps:
    - checkout
    - run:
        name: build
        command: |
          nix-build

  test-webapp:
    working_directory: ~/repo
    parallelism: 1

    docker:
      - image: node:10.15.3-alpine

    steps:
      - checkout

      - restore_cache:
          key: dep-{{ checksum "client/package-lock.json" }}

      - run:
          name: install javascript dependencies
          command: |
            cd client
            npm install

      - save_cache:
          key: dep-{{ checksum "client/package-lock.json" }}
          paths:
          - client/node_modules

      - run:
          name: run tests
          command: |
            cd client
            npm run test

      - run:
          name: verify a full build
          command: |
            cd client
            npm run build

workflows:
  version: 2
  build_all:
    jobs:
      - build-rust-lfs
        # - build-rust-nix
      - test-webapp
