version: 2
jobs:
  build:
    working_directory: ~/repo
    parallelism: 1

    docker:
      - image: circleci/rust:1.39

    steps:
      - checkout

      - restore_cache:
          keys:
            - dep-{{ checksum "Cargo.toml" }}

      - run:
          name: build
          command: cargo build --release

      - run:
          name: test fitnesstrax-lib
          command: |
            cd fitnesstrax-lib
            RUST_BACKTRACE=1 cargo test

      - run:
          name: test the GTK app
          command: |
            mkdir var
            RUST_BACKTRACE=1 cargo test

      #- run:
          #name: copy components
          #command: |
            #mkdir -p dist/opt/fitnesstrax/bin
            #mkdir -p dist/opt/fitnesstrax/client
            #cp server/target/release/app dist/opt/fitnesstrax/bin/fitnesstrax-server
            #cp client/dist/* dist/opt/fitnesstrax/client

      #- run:
          #name: make deb
          #command: cd dist && fpm -f -s dir -t deb -n fitnesstrax -v `git describe --abbrev=4 HEAD` opt

workflows:
  version: 2
  build:
    jobs:
      - build
